import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/home.module.scss";
import Card from "@/components/Card";
import Logo from "@/public/logo.webp";
import { getGenerationPage } from "@/utils/axios";
import { useQuery } from "react-query";
import InputSearch from "@/components/InputSearch";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [generation, setGeneration] = useState("1");
  const {
    isLoading,
    isError,
    error,
    data: pokes,
  } = useQuery(
    ["generation/", generation],
    () => getGenerationPage(generation),
    {
      keepPreviousData: true,
    }
  );

  const slicedList = pokes?.pokemon_species.slice(0, 10);

  return (
    <>
      <Head>
        <title>Pokédex King Tide Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.logoContainer}>
          <img className={styles.logo} src="/logo.webp" alt="Pokemon Name" />
        </div>
        <InputSearch placeholder="Search Pokémon" />
        <section className={styles.container}>
          {slicedList?.map((el, i) => {
            return <Card name={el.name} />;
          })}
        </section>
      </main>
    </>
  );
}
