import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import { Inter } from "next/font/google";
import styles from "@/styles/home.module.scss";
import Card from "@/components/Card";
import Logo from "@/public/logo.webp";
import { getGenerationPage } from "@/utils/axios";
import { useQuery } from "react-query";
import InputSearch from "@/components/InputSearch";
import Checkbox from "@/components/Checkbox";
import AddFav from "@/components/AddFav";
import Paragraph from "@/components/Paragraph";
import Title from "@/components/Title";
import { selectaddFavs } from "@/store/favs";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [generation, setGeneration] = useState("1");
  const [numElements, setNumElements] = useState(9);
  const [pokemones, setPokemones] = useState([]);
  const [loading, setLoading] = useState(false);
  const [showFavorites, setShowFavorites] = useState(false);
  const [loadMore, setLoadMore] = useState(true);
  const arrFavs = useSelector(selectaddFavs);
  const increment = 9;
  const {
    isLoading,
    isError,
    error,
    data: pokes,
  } = useQuery(
    ["generation/", generation],
    () => getGenerationPage(generation),
    {
      keepPreviousData: true,
    }
  );

  useEffect(() => {
    let arrNew = pokes?.pokemon_species.slice(0, numElements);
    if (arrNew) {
      setPokemones([...arrNew]);
    }
  }, [isLoading, numElements, generation, pokes]);

  useEffect(() => {
    handleScroll();
  }, []);

  const handleSearch = (e: React.ChangeEvent<HTMLInputElement>): void => {
    let query = e.target.value.toLowerCase();
    let pokeFiltered: Pokemon[] = [];

    if (query.length > 3) {
      setPokemones(
        pokes?.pokemon_species.filter((el: Pokemon) => el.name.includes(query))
      );
    } else {
      setPokemones(pokes?.pokemon_species.slice(0, numElements));
    }
  };

  const handleScroll = (): void => {
    const { scrollTop, clientHeight, scrollHeight } = document.documentElement;
    if (scrollTop + clientHeight >= scrollHeight) {
      setNumElements((prevNumElements) => prevNumElements + increment);
    }
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  };

  const toogleGen = (): void => {
    setGeneration(generation === "1" ? "2" : "1");
    setNumElements(9);
  };

  const showFavs = (): void => {
    let toogle = !showFavorites;
    setShowFavorites(toogle);
    setLoadMore(toogle);
    if (toogle) {
      let arrNew = pokes?.pokemon_species;
      let filteredArray = arrNew.filter((el: { name: string }) =>
        arrFavs.includes(el.name)
      );
      setPokemones([...filteredArray]);
    } else {
      let arrNew = pokes?.pokemon_species.slice(0, numElements);
      setPokemones([...arrNew]);
      setLoadMore(true);
    }
  };

  return (
    <>
      <Head>
        <title>Pokédex King Tide Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.logoContainer}>
          <img className={styles.logo} src="/logo.webp" alt="Pokemon Name" />
        </div>
        <div className={styles.searchContainer}>
          <div>
            <Paragraph text="Favs" colorVariant="white" />
            <AddFav colorVariant="white" onAddToFavs={showFavs} />
          </div>
          <InputSearch
            onChange={(e) => handleSearch(e)}
            placeholder="Search Pokémon"
            className={styles.search}
          />
          <Checkbox onChange={toogleGen} label="Gen. 2" colorVariant="white" />
        </div>
        <section className={styles.container}>
          {pokemones?.length === 0 ? (
            <div className={styles.searchContainer}>
              <Title text="No items" colorVariant="white" />
            </div>
          ) : (
            pokemones?.map((el, i) => {
              return <Card key={i} name={el.name} />;
            })
          )}
        </section>
      </main>
    </>
  );
}
